# Generated by Django 4.1.4 on 2022-12-14 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
