# Generated by Django 4.1.4 on 2022-12-14 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_post_created_on_alter_user_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='publication_date',
        ),
    ]
