# Generated by Django 4.1.4 on 2022-12-15 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_rename_created_on_post_publication_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
